// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes" // #nosec G101
)

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Token string `json:"token"`
	User  User   `json:"user"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// SignInRequest defines model for SignInRequest.
type SignInRequest struct {
	CaptchaToken *string             `json:"captchaToken,omitempty"`
	Email        openapi_types.Email `json:"email"`
	Password     string              `json:"password"`
}

// SignUpRequest defines model for SignUpRequest.
type SignUpRequest struct {
	CaptchaToken *string             `json:"captchaToken,omitempty"`
	Email        openapi_types.Email `json:"email"`
	Password     string              `json:"password"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time           `json:"created_at"`
	Email     openapi_types.Email `json:"email"`
	Id        openapi_types.UUID  `json:"id"`
}

// SignInJSONRequestBody defines body for SignIn for application/json ContentType.
type SignInJSONRequestBody = SignInRequest

// SignUpJSONRequestBody defines body for SignUp for application/json ContentType.
type SignUpJSONRequestBody = SignUpRequest
