run:
  timeout: 5m
  tests: false

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

linters-settings:
  govet:
    enable:
      - shadow
