run:
  concurrency: 4
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - dupl
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - dogsled
    - nakedret
    - exportloopref
    - gocritic
    - goprintffuncname
    - prealloc
    - rowserrcheck
    - stylecheck
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  govet:
    check-shadowing: true

